# Site settings
title: Nabilzhang
email: dumuqiao0317@gmail.com
description: "Nabilzhang's Site"
baseurl: ""
url: "http://nabilzhang.github.io/"
github_username:  nabilzhang

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
highlighter: rouge

future: true